**Numpy and Pandas**

In [ ]:
import numpy as np

In [ ]:
#1:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
new_a=a.reshape(2,5)
new_a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#2.
b=np.arange(1,21)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
print(b[5:15])

[ 6  7  8  9 10 11 12 13 14 15]

In [ ]:
#3
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
print(np.mean(b))
print(np.median(b))
print(np.std(b))

10.5
10.5
5.766281297335398

In [ ]:
#4.
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x
print(x)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

In [ ]:
y=np.array([2,4,6,8])
y
print(y)
print(y.shape)

[2 4 6 8]
(4,)

In [ ]:
result=x-y
print(result)

[[-1 -2 -3 -4]
 [ 3  2  1  0]
 [ 7  6  5  4]]

In [ ]:
#5.

import pandas as pd

In [ ]:
data={'Name':['Amala','Gabriel','Dona','Nihala','Jithin','Denna','Manu','Aishu','Jacob','Alana'],
      'Age':[28,26,25,24,22,21,29,27,23,30],
      'Gender':['Female','Male','Female','Female','Male','Female','Male','Female','Male','Female']
      }
df=pd.DataFrame(data)
df

      Name  Age  Gender
0    Amala   28  Female
1  Gabriel   26    Male
2     Dona   25  Female
3   Nihala   24  Female
4   Jithin   22    Male
5    Denna   21  Female
6     Manu   29    Male
7    Aishu   27  Female
8    Jacob   23    Male
9    Alana   30  Female

In [ ]:
df.shape

(10, 3)

In [ ]:
#5.1
df['Occupation']=['Programmer','Manager','Analyst','Analyst','Manager','Programmer','Manager','Programmer','Analyst','Analyst']
df

      Name  Age  Gender  Occupation
0    Amala   28  Female  Programmer
1  Gabriel   26    Male     Manager
2     Dona   25  Female     Analyst
3   Nihala   24  Female     Analyst
4   Jithin   22    Male     Manager
5    Denna   21  Female  Programmer
6     Manu   29    Male     Manager
7    Aishu   27  Female  Programmer
8    Jacob   23    Male     Analyst
9    Alana   30  Female     Analyst

In [ ]:
#5.2
df[df['Age']>=30]

    Name  Age  Gender Occupation
9  Alana   30  Female    Analyst

In [ ]:
#5.3
df.to_csv('assignment.csv',index=False)
df2=pd.read_csv('assignment.csv')
print(df2)

      Name  Age  Gender  Occupation
0    Amala   28  Female  Programmer
1  Gabriel   26    Male     Manager
2     Dona   25  Female     Analyst
3   Nihala   24  Female     Analyst
4   Jithin   22    Male     Manager
5    Denna   21  Female  Programmer
6     Manu   29    Male     Manager
7    Aishu   27  Female  Programmer
8    Jacob   23    Male     Analyst
9    Alana   30  Female     Analyst